# Generated by Django 5.1.4 on 2025-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='facebook_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='google_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='photos',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='teams',
            name='twitter_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
