# Generated by Django 5.1.4 on 2025-01-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_teams_created_date_teams_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
